### ISSUE TITLE
MK2.5S:MMU2S Configuration

### ISSUE THREAD

**Issue by habitforming11** [TheZeroBeast/MM-control-01#135] opened 2019-09-13 01:48 UTC
Please consider a MK2.5S compatible variant of the lastest TZB MMU2s firmware.  Unfortunately my technical ability in coding is nearly zero, but I will be happy to support through detailed testing.

**Comment by TheZeroBeast** [comment] 2019-09-13 08:44
Hey mate, I'll try have a look this weekend and hack together a starting point for you to flash and try.
What language do you prefer for the build?

**Comment by habitforming11** [comment] 2019-09-13 15:35
Very much appreciated!  English, please.

I just found that Prusa failed to send the mk2.5 IR sensor cable in my kit, so I won't have a printer ready to use for a few more days.

**Comment by TheZeroBeast** [comment] 2019-09-14 04:48
English, can do.
Ah, damn, no problem. Will be interesting 👍

**Comment by TheZeroBeast** [comment] 2019-09-22 21:07
Hey @habitforming11,

I'll post a printer hex later today, I have it compiling for MK2.5S now.

**Comment by habitforming11** [comment] 2019-09-22 22:26
glad to hear it!  Prusa threw me several curve balls, so i all don't have a completely functioning mmu.  first was missing two harnesses, now I learned my mk2s heat break is too large inside diameter which is causing massive unloading / loading difficulties.  should have the right heat break on Tuesday.

do you have any specific testing you need me to do?  i can load firmware, check calibration, etc.

also, i am running the bear extruder which is 7mm taller than mk2.5S extruder. will that be a problem?

**Comment by TheZeroBeast** [comment] 2019-09-22 22:36
Oh lovely.....
The correct heatbreak(MK3) makes a big difference, definitely needed.

If you can let me know if the homing worked reliably and only the desired two taps for selector and idler. With TMC2130s running on 12v instead of 24v it may not work as intended.

Apart from that just put it through it's paces and if you come across an issue rill out the bug report template.

With the bear mod just ensure you don't go higher than you are able to when slicing.
Your Slicer profile can even be changed to limit max height.

**Comment by habitforming11** [comment] 2019-09-22 22:46
can you explain this sentence "and only the desired two taps for selector and idler"?

**Comment by TheZeroBeast** [comment] 2019-09-22 22:58
Sure can.

When the printer connects to the MMU2S unit it will home.
This results in two audible taps/knocks each when they hit their respective endstops.

**Comment by habitforming11** [comment] 2019-09-23 01:04
OK that makes total sense.  That sounds a whole lot better than the two sets of about 10 knocks that it does currently.

**Comment by habitforming11** [comment] 2019-09-23 01:07
Also as I mentioned I am a complete amateur at github.  Have you posted the 2.5 compatible firmware and if so, where do I find it?

**Comment by TheZeroBeast** [comment] 2019-09-23 01:22
haha, I konw right, PRUSA just runs into the endstop for a period of time and assumes it's homed even though TMC2130 drivers have stallguard for virtual endstops. Slaps face

I haven't yet, are you keen, I'll try remote into my home computer and upload to this thread soon.

**Comment by habitforming11** [comment] 2019-09-23 01:27
Don't go out of your way on my account if you don't want.  I was sitting here with a few free hours thinking about getting the machine torn down for the heat break swap, but if you had something ready to test and we're just looking at initialization, I figured I'd give it a go beforehand.  Doesn't make much difference to me, but if you're anxious for a report I'm ready to test.

**Comment by TheZeroBeast** [comment] 2019-09-23 01:42
Here we go, so load this into the printer, then load the MMU2S hex from [here](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases)
[TZB-MK2.5S-3.0.0-BN2450.hex.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3640386/TZB-MK2.5S-3.0.0-BN2450.hex.zip)

Yeah, keen to know how it goes, I have an old MK2S that would like some MMU2S oneday lol

**Comment by habitforming11** [comment] 2019-09-23 03:22
It does 4 double taps of the idler upon startup.  Now investigating the flashing light and where to proceed.  I'll update as I continue.

Also I have a bug report to post, incoming.

**Comment by habitforming11** [comment] 2019-09-23 03:37
I now have a flashing green (or flashing red if I push filament through) on lane 2, the currently selected lane.  The middle button appears to rehome the idler, the other buttons are unresponsive.  I've looked through the TZB-MMU2S-Firmware wiki, and I cannot find what this error state is or how to proceed.

EDIT - More importantly, MMU is not detected by MK2.5S

**Comment by TheZeroBeast** [comment] 2019-09-23 03:54
Were you able to get them both flashed with this firmware? I see in your bug report you were having issues flashing the MMU2S after the MK2.5S.

The middle button attempts to load filament on that channel (two attempts if unsuccessful)
Initially it should home both the selector and idler after middle button press.
Then it should push filament to FINDA and then back to parking location.
If it isn't detected at FINDA then red, green lights on that channel alternate to say error (I'll add **wiki** details for this soon)

In this error state middle will retry to load filament (Note: on second try if it fails it doesn't go into error state)

If the idler and selector appear to be doing the correct movements and engaging the filament then check your FINDA is tripping when filament is present.

Maybe dropbox a short video so I can see the sequence.

**Comment by habitforming11** [comment] 2019-09-23 04:15
While the mk2.5 was flashed with the prusa firmware, I flashed TZB onto the MMU.  Following that, I flashed TZB onto the mk2.5.

Now when I power up, the lane 2 green LED is flashing, but no other activity occurs.  If I push the middle button, the idler re-homes and returns to lane 2, lane 2 green LED continues to flash, but the bondtech motor never moves at all.  Left/right buttons do nothing.  Mk2.5 support screen says "MMU not connected"

**Comment by habitforming11** [comment] 2019-09-23 04:18
To be clear, the selector never moves (or attempts to).  The idler is the only stepper that does anything following power up/reset.

**Comment by TheZeroBeast** [comment] 2019-09-23 04:20
Hmmm, leave it with me @habitforming11, I'll review the comms pins for the two boards, probably missed something I need to set specifically for the MK2.5S

**Comment by TheZeroBeast** [comment] 2019-09-23 08:49
I made a small change to the mmu2s init of comms, might be why they're not communicating, can you flash it onto the printer and see. Also, just to make sure, you have TZB-MMU2S-3.0.0-RC3 flashed on the MMU2S right?

Do you have access to the serial logs, prontoface or OctoPrint, that would be the next helpful thing to diagnose what's happening.

[TZB-MK2.5S-3.0.0-BN2451.hex.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3641286/TZB-MK2.5S-3.0.0-BN2451.hex.zip)

**Comment by habitforming11** [comment] 2019-09-23 14:26
That's correct, I did have TZB-MMU2S-3.0.0-RC3 flashed onto the MMU.  I was able to do that by flashing it first when the printer still had prusa firmware installed.

With BN2451 I am able to see MMU2S device on my PC, but flashing TZB-MMU2S-3.0.0-RC3 onto it failed so far.  Still testing.

**Comment by habitforming11** [comment] 2019-09-23 14:30
Following power off/on of the printer, the display only shows two rows of solid boxes.  No text.

I flashed BN2451 yet again, but still only two rows of squares are displayed.  Unable to control printer at all.

**Comment by TheZeroBeast** [comment] 2019-09-23 19:26
Hmm, interesting. I'll have to have a think about it....
Realistically I need a MK2.5S test rig, I'll see what I can sort out.

**Comment by AbeFM** [comment] 2019-09-23 21:06
> To be clear, the selector never moves (or attempts to). The idler is the only stepper that does anything following power up/reset.

I have had all sorts of issues that boil down to bad connections. The connectors on the MMU are garbage, maybe ok for chasis wiring, but enough to cause issues if they ever get moved/bumped.... while being installed on something that you have to work on all the time to make work and lives in a hinge that gets moved hundreds of times per print.

In short: The times I've had a motor not work, I wiggle (or reconnect) all the connectors on the back of the MMU, half the time this brings it back. Look for wires not quite in the connector. I would do it while powered off to ensure you don't break something.

Not saying it is what you're seeing here, but other times where no answer made sense, that worked.

**Comment by habitforming11** [comment] 2019-09-23 21:11
@abefm good info. in this case it's a matter of the firmware though. switching back to prusa firmware, everything functions as expected.

**Comment by TheZeroBeast** [comment] 2019-09-23 21:27
Yeah, @AbeFM, not the best cabling setup hey.
The annoying difference that's causing issues is the lack of MMU_HW_RESET on the MK2.5S, not a problem if I had a setup to chuck the old logic analyser on but lacking the HW at present.

**Comment by TheZeroBeast** [comment] 2019-09-25 09:35
I've got another test for you @habitforming11, hopefully a connection between printer and MMU2S this time.  

[TZB-MMU2S-3.0.0-RC3-BN352.hex.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3651702/TZB-MMU2S-3.0.0-RC3-BN352.hex.zip)  
[TZB-MK2.5S-3.0.0-BN2454.hex.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3651710/TZB-MK2.5S-3.0.0-BN2454.hex.zip)

Flashing as per the [Wiki](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/wiki/Flashing-Procedure) videos 👍

**Comment by habitforming11** [comment] 2019-09-25 20:00
I am still getting two rows of solid boxes on the printer LCD after flashing "TZB-MK2.5S-3.0.0-BN2454.hex"

Followed the instructions on your wiki exactly.  Printer also never self restarts after firmware install successfully completed.  This is before attempting to flash the TZB MMU firmware.  Results on that to follow...

**Comment by habitforming11** [comment] 2019-09-25 20:04
Flashing MMU firmware "TZB-MMU2S-3.0.0-RC3-BN352.hex" was successful via your wiki instructions.  However, the printer display is now blank after initialization, and MMU has flashing amber LED on lane 2 (Lane 2 is currently loaded to nozzle).

**Comment by habitforming11** [comment] 2019-09-25 20:06
Octoprint was able to establish a connection, though the printer display is still blank.  Here is terminal readout:

Connecting to: /dev/ttyACM0Changing monitoring state from "Detecting serial port" to "Opening serial port"Connected to: Serial<id=0x72395750, open=True>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitorStarting baud rate detection...Changing monitoring state from "Opening serial port" to "Detecting baudrate"Trying baudrate: 115200Send: N0 M110 N0*125Recv: echo: TZB3.0.0-2454Recv: echo: Last Updated: Sep 25 2019 19:16:30 | Author: (none, default config)Recv: Compiled: Sep 25 2019Recv: echo: Free Memory: 1786  PlannerBufferBytes: 1392Recv: echo:Hardcoded Default Settings LoadedRecv: adc_initRecv: W25X20CL not responding.Recv: CrashDetect ENABLED!Recv: FSensor ENABLEDRecv: echo:SD init failRecv: echo:busy: paused for userPrinter seems to support the busy protocol, will adjust timeouts and set busy interval accordinglyRecv: echo:busy: paused for user

**Comment by AbeFM** [comment] 2019-09-25 20:22
Just to double check - you need to flash both with a matching set of firmware. If you only do one, it breaks. Ideally, printer would say so ("Warning: MMU Firmware Mismatch").

**Comment by habitforming11** [comment] 2019-09-25 20:39
Understood. As explained in my second reply above, i did subsequently flash mmu also.  Printer display remains blank.

**Comment by TheZeroBeast** [comment] 2019-09-25 22:10
Ah, damn, I left a delay in that's blocking MK2.5S booting, I'll send a set in a couple hours with this removed.

**Comment by TheZeroBeast** [comment] 2019-09-26 02:01
TZB-MK2.5S-3.0.0-BN2457.hex.zip

**Comment by habitforming11** [comment] 2019-09-26 04:07
I'll try to get to it tomorrow.  After a very successful night getting things back together and working properly, I found an issue with my selector.  Now to print a new one to replace it with.  Making progress though!

**Comment by TheZeroBeast** [comment] 2019-09-26 05:21
No problem, sounds good.

Interesting, what issue did you find with your selector, I'm still on my stock one, must be luck?

**Comment by AbeFM** [comment] 2019-09-26 07:03
> I'm still on my stock one, must be luck?

THAT's interesting. I'm using JTLX's easy to clean out selector rocks. I don't really like the magnet some people put in.

**Comment by TheZeroBeast** [comment] 2019-09-26 10:02
Dman, I was mixed up, I'm on my stock drum/idler. My selector is one I have on Thingiverse with M10 passthrough and 8mm neo magnet to assist ball drop.

So, I just worked out I compiled MK2.5S FW incorrectly, tested on my old girl (MK2.5) and got it booting 👍

I also merged to STOCK_COMMIT_NR:3274


I have attached the hex files, hopefully it'll also allow your MMU2S to connect.
[Archive.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3657193/Archive.zip)

**Comment by habitforming11** [comment] 2019-09-26 11:20
I'm using "Selector_Magnet_Window_PC10Passthrough.stl", can't remember the author.  When it prints, it bridges across the filament exit where the passthrough fitting attaches, and he says you have to drill that part out.  Not understanding exactly what the function was when I first built it, I drilled it for the 3mm OD of the ptfe tubing, but it should have been 1.9-2.0mm for just the filament.  Consequently, the filament periodically catches on the edge of the ptfe tubing, gradually collapsing it inward and causing load failures.  I got through about 60 filament changes last night before it failed though - I new personal best!

**Comment by TheZeroBeast** [comment] 2019-09-26 11:24
Awesome to hear you’re kicking goals.

Consider the selector I designed with m10, no drilling requirements and hopefully less catching filament.

I’ve done over 1000 change PLA prints without issue through it.

**Comment by habitforming11** [comment] 2019-09-26 15:19
Do you have a link to your selector?  I looked on your thingiverse page but I don't see a selector.

Edit - nevermind, I just found it in your extruder design page

**Comment by TheZeroBeast** [comment] 2019-09-26 18:57
Yeah, I'll move the MMU2S portion into it's own design on thingiverse and prusaprinters

It hides with my MK3 extruder mod

**Comment by AbeFM** [comment] 2019-09-26 20:18
GOOD!

I complain a lot so I didn't bring that one up. :-)

The JTLX one I'm running has many thousands of changes on it, I can recommend it. Haven't tried Rob's.

**Comment by habitforming11** [comment] 2019-09-27 04:34
![tzb_selector_section](https://user-images.githubusercontent.com/55253710/65742523-8ddd2800-e0be-11e9-922f-8d1217b53bc4.JPG)
It looks like your design also has that solid wall where the filament exits the selector.  Sorry for OT!

**Comment by habitforming11** [comment] 2019-09-27 04:38
![tzb_selector_section2](https://user-images.githubusercontent.com/55253710/65742645-0d6af700-e0bf-11e9-95c0-29c477d39afb.JPG)

**Comment by TheZeroBeast** [comment] 2019-09-27 04:50
Damn, I'll review tonight @habitforming11, 12 month old design lol

Any chance to try load the fw from last night?

**Comment by TheZeroBeast** [comment] 2019-09-27 12:29
Fixed her up, added blade section back in.
Having't printed to test yet but should be good.

[<img src="https://user-images.githubusercontent.com/20939095/65719374-09ec6580-e0e9-11e9-9624-aa239ac53aa7.PNG" height="300">\
TZB MMU2S Selector M10 No Blade](https://www.thingiverse.com/thing:3882042)

**Comment by habitforming11** [comment] 2019-09-27 13:05
I just had a chance to flash the firmware. Flashing procedure went well, and the printer display is working as normal now.  However with the MMU2S, it continually does the double tap homing procedure (over, and over, and over, and over, etc) and the printer support screen shows MMU as "n/a".  Making progress though!

**Comment by AbeFM** [comment] 2019-09-27 21:02
TZB - it would be nice to have a github thread/whatever for the physical designs - instead of threading them into discussions about firmware. Even just make an issue called "selector issues" and start with a link to the TV page?

I've debated - one of my most common failures is filament squirting out from the gap where the blade lives. Making that tighter and with a bigger chamfer seems like it would improve loading.

The downside with doing that is that the current design allows you to easily pull the filament free and service it. You have to weight the issues caused by the gap against the increased difficulty of fixing other issues which might get worse without a pain-free escape path for filament.

Similarly, there's a lot of room for improvement in the MMU - filament gets tangled on gears too often.

As the firmware improves, these are less of an issue.

**Comment by TheZeroBeast** [comment] 2019-09-27 22:22
Awesome @habitforming11,

Progress indeed, the mmu2s is failing to home, difference of voltage showing it’s head.
I’ll make some changes to the mmu2s code for you to try 👍

Have you tried my selector, I minimised the gaps to the case, it’s been working great.

Yes, we can create a thread for different hardware mods to discuss, I’ll create a tag for them now.

**Comment by TheZeroBeast** [comment] 2019-10-01 06:52
Ok, I have a plan of attack, I'll be hooking up my bench supply @ 12v this weekend to my MMU2S to tune Stallguard which is why it keeps trying to home.

I'll get a new build to you shortly after, should be one of the only things the voltage differences will affect.

**Comment by AbeFM** [comment] 2019-10-01 17:41
On my mk3S/mmu2s if I say "home all" it consistently puts the selector on
pos A, the drum on pos B, feeds out the wrong filament next to selector.

If you stop it, it'll move on to the next one (I believe the printer
doesn't do any checks, so it just goes on), each time the drum is off by
one so you get all your filaments sticking out of the machine and the
selector moving over to snap them off.

I never liked how 'load all' worked, but it works worse now. :-P

Otherwise I've had few issues.

**Comment by TheZeroBeast** [comment] 2019-10-01 18:49
Can you open a bug report for that @AbeFM with the template so I can get it fixed?

Edit: Hey @AbeFM, I just loaded all five and double checked half a dozen time from fresh boot to after ejects and loads and always did all five from left to right as it should. Is it still happening on the latest release?

**Comment by TheZeroBeast** [comment] 2019-10-05 09:10
@habitforming11,

I've had a win, I pipped 12v into my MMU2S and setup voltage reading to identify when it's on a 12v system and adjust itself.

I'm just running a test print then I'll post the compiled hex files.

![IMG_1698](https://user-images.githubusercontent.com/20939095/66252827-7e876a00-e7a3-11e9-9a3d-83bbb67e5c1e.jpg)

**Comment by TheZeroBeast** [comment] 2019-10-05 10:43
Hi @habitforming11,

Can you please try this set, from what I can tell it should be fully functional on your MK2.5S setup.
If so I'll add it to the releases page 👌👍
[TZB-300-MK25S-Bundle.zip](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3693121/TZB-300-MK25S-Bundle.zip)

**Comment by habitforming11** [comment] 2019-10-06 15:15
I should have some time to give it a whirl this evening.

**Comment by habitforming11** [comment] 2019-10-06 16:33
Hi @TheZeroBeast 

Happy to report the firmware has been successfully loaded, and the MMU and printer both appear happy so far.  I haven't had a chance for a test print, but the MMU homes properly, the display on the printer is working, and the MMU properly shows as connected.

**Comment by habitforming11** [comment] 2019-10-06 17:37
I just did a test print, have a strange issue.  The MMU idler isn't moving off of the active filament during a print.  I can hear the filament clicking against the bondtech in the mmu, and see the shaft turning from time to time as filament is being pulled through.  This happened on both lane 1 & 2 during a test print just now.  The load process selects lanes correctly, so I don't think it's a mechanical issue.

**Comment by TheZeroBeast** [comment] 2019-10-08 00:45
Hi @habitforming11,

That's awesome progress!! 👏

I have a few questions.
 1. How many full rotations past flush are the two idler tension bolts on the MMU2S?
 2. Can you try grab the serial logs from the printer for a load sequence?
 3. Does the load to nozzle in the menu work and allow you to unload afterwards?

**Comment by habitforming11** [comment] 2019-10-08 00:52
for the serial logs will that work if i just do load from the printer screen, or does it need to be during a print?

once i get to the printer in about 30 min I'll answer all of the above.

**Comment by TheZeroBeast** [comment] 2019-10-08 00:59
If the load_to_nozzle works from the menu it'll need to be from a print load thanks mate.
When you get time 👍

**Comment by habitforming11** [comment] 2019-10-08 02:25
1.  Half a rotation past flush
2.  I will post in a separate reply
3.  I now cannot load as the printer no longer acknowledges the MMU.  I was doing "load all" and must have hit the incorrect button to skip each empty lane.  Now lane 5 red & green flash every time the MMU boot finishes, even after a reset.  I press the middle button and the MMU returns no normal state, but as soon as I power off or reset MMU it comes on with lane 5 red/green flash again.

**Comment by TheZeroBeast** [comment] 2019-10-08 02:45
Cool, might need to go further, half a rotation doesn't apply much force to the filaments to engage.
Your MMU2S is disabled in the Service Position (allowing use of printer without MMU2S)
This is a TZB FW feature.
Use Left button to direct back onto a channel and reset printer to reconnect the two devices.

**Comment by habitforming11** [comment] 2019-10-08 04:22
Wow, that's a very useful feature!

1. 1.5 turns past flush
2. to follow
3. Load to nozzle is select-able.  The load is successful, however the MMU extruder motor gets dragged forward and backward during load/unload.  Unload is also completely successful.

**Comment by habitforming11** [comment] 2019-10-08 04:33
Here is the log for item 2
 
[tzb_bn2462_BN358_log.txt](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/files/3700731/tzb_bn2462_BN358_log.txt)

I have also taken two videos that I will upload now.

**Comment by habitforming11** [comment] 2019-10-08 04:49
video of initial load, and of first filament swap

https://drive.google.com/file/d/1B92-2giY3KKgaqNLeZ_n7MUPwQ8ieYHt/view?usp=sharing

https://drive.google.com/file/d/1BDlPciolJ8HjPprmJjbjyLOnv1qH1oCx/view?usp=sharing

**Comment by TheZeroBeast** [comment] 2019-10-08 13:41
So......
It appears to me like you need to do your Bowden calibration as the MMU2S is fighting to push more down a nonexistant tube.
Check out my wiki [post](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/wiki/Bowden-Length-Calibration), the calculated values differ for my FW.

Hopfully

**Comment by habitforming11** [comment] 2019-10-08 15:10
I can certainly do that again, you're correct that it's probably out of spec at least some.  I had to replace that tube a week or two ago as the old one got chewed up from all the disassembly/reassembly.

However, I still see the MMU extruder motor getting dragged around during printing the actual part, not only during filament changes.  Shouldn't the selector index over to the next lane, so that the in-use lane can pass freely through MMU?

**Comment by TheZeroBeast** [comment] 2019-10-08 15:17
I’m not sure what would happen if the mmu2s tries to feed more and goes over the load.
My guess is the load never acts on the final command from the printer due to not being at that stage and never disengages the filament.

Try doing the cal at least twice to ensure you’re filament is at the middle of the bondtech gears 👍

**Comment by habitforming11** [comment] 2019-10-08 18:05
I had assumed the IR sensor trigger would tell the MMU that filament reached the print head anyway.  I'll calibrate the length and see if the result is any different.

**Comment by habitforming11** [comment] 2019-10-08 18:12
disregard

**Comment by TheZeroBeast** [comment] 2019-10-08 21:56
Lane one is your one and only for cal 😊👍

**Comment by AbeFM** [comment] 2019-10-09 00:39
It appears, to save time, to send filament most of the way at high speed,
then it monitors the IR sensor.

                  Thanks!
                          -Abe.

**Comment by habitforming11** [comment] 2019-10-09 01:19
From your wiki description, it sounded like it stayed at lane 4.  Once I actually got to the printer & did it, the process was quite clear.

And with that, I believe the printer is now functioning properly.  I guess the MMU extruder was getting dragged along because of existing ridges in the filament from the bondtech.  Once it went through 2-3 tool changes, the funny noises stopped and the MMU extruder was no longer getting dragged around anymore.

Now I need to spend some time getting tips dialled in for my matterhackers white pla, and I might actually be in range of my first successful MMU print!

THANK YOU @TheZeroBeast

**Comment by TheZeroBeast** [comment] 2019-10-09 01:37
WOOOO!!!!! Thanks great, good work. I'll release the MK2.5S code soon👍

**Closed as completed by TheZeroBeast** 2019-10-09 01:37 UTC
Labels: enhancement

**Comment by habitforming11** [comment] 2019-10-09 02:07
What is the logic behind the "heatbreak jam/clog" message?  I am getting that dragging effect on the MMU extruder again, and routinely getting heatbreak jam/clog notification.  On inspection nothing is apparently amiss.

**Comment by TheZeroBeast** [comment] 2019-10-09 02:16
Double check your IR_SENSOR is giving solid readings as if it's tripping on/off while loading it'll report a Jam.

Jam logic goes as follows within the load window (ie. filament has done major load and now both MMU2S and Printer are extruding so printer to grab)
1. Printer is turning extruder no filament in gears yet (IR_SENSOR must not give false positives)
2. Filament goes into gears which flags the IR_SENSOR
3. Filament is then extruded into the heatbreak a known amount but not to the hotzone
4. Filament is retracted a little less than the extruded distance in step 3
   - If there was a jam in the heatbreak then step 3 would slip and step 4 would release filament
5. Check if gears still have filament, is the IR_SENSOR still tripped. If not report error and await human intervention

I have never used the stock tower extruder design, the one I did up is very solid.
In either case you have to adjust your extruder to get solid IR_SENSOR readings for this and Stock FW.

Also good to note that the above procedure is directly from Stock code, I haven't modified that in my FW.

**Comment by AbeFM** [comment] 2019-10-09 02:36
https://photos.app.goo.gl/avo4wobHQvNUfKva8 this allowed me to fix my issue.

                  Thanks!
                          -Abe.

**Comment by TheZeroBeast** [comment] 2019-10-09 02:59
Nah, no need to overcomplicate it. Simple, simple

**Comment by habitforming11** [comment] 2019-10-09 04:28
Ok, I had suspected the IR sensor was the issue, thank you for the confirmation.  I wish there was a centralized location that explained all of these details.  It sure would make troubleshooting a whole lot easier.

**Comment by habitforming11** [comment] 2019-10-09 04:29
@AbeFM I see the issue in the video, but what fixed it?

**Comment by TheZeroBeast** [comment] 2019-10-09 04:37
Hey @habitforming11,
I'm working on doing up steps and videos for troubleshooting in my wiki.

The MMU2S handbook that is sent out with the device covers most basic troubleshooting but I find videos convey a lot more when troubleshooting.

TZB-FW also has a lot of handy troubleshooting features that really only videos can convey.

**Comment by AbeFM** [comment] 2019-10-09 06:44
I just meant it's good to check if it's monotonic.

                  Thanks!
                          -Abe.

**Comment by AbeFM** [comment] 2019-11-04 00:37
Sorry for the late reply! Er, I printed a couple different flags, and ended
up putting foil tape on the tip. The shape of the tip is important, but I
didn't get anything definitive enough to publish.
