### ISSUE TITLE
3.9.0 cut feature not enabled in TZB?

### ISSUE THREAD

**Issue by Naugrimohtar** [TheZeroBeast/MM-control-01#187] opened 2020-11-23 16:35 UTC
I am looking to enable the MMU2s cutter using the settings that seem to be released in the 3.9.0 Prusa firmware release but I cannot seem to find them in TZB. Is this implemented? For example see timestamp ~12:30 in this video by Chris' Basement -- https://www.youtube.com/watch?v=LpoCYmSb7wo&ab_channel=ChrisRiley

**Comment by TheZeroBeast** [comment] 2020-11-24 04:55
Not a bug mate, different firmware. Possibility to add in the future.

**Comment by XRyu** [comment] 2020-11-24 21:38
@TheZeroBeast Welcome back on board Captain :D Nice to see you back :)

**Comment by TheZeroBeast** [comment] 2020-11-24 21:47
Never gone, just GitHub notifications don’t seam to reach me reliably😂

**Comment by XRyu** [comment] 2020-11-24 21:49
Haha 😂🤣 i know its OT, but are you gonna merge the latest stuff like Ruhkuka did and update your versions? :D

**Comment by TheZeroBeast** [comment] 2020-11-24 21:51
Yes I will be merging, I just haven’t needed to yet from 3.9.0
Let me go review 3.9.1 changes

Edit: yeah, 3.9.2 now I see and yes, a few good improvements we could benefit from 🤔

**Comment by TheZeroBeast** [comment] 2021-01-19 03:30
FYI @Naugrimohtar, I'm coding cut now for testing and release in TZB 3.2.0 release.

**Comment by Naugrimohtar** [comment] 2021-01-19 13:13
Excellent! Thank you!

**Comment by TheZeroBeast** [comment] 2021-01-22 09:02
[Resolved in Release 3.2.0](https://github.com/TheZeroBeast/TZB-MMU2S-Firmware/releases/tag/3.2.0)
Please comment if you have any questions.

**Closed as completed by TheZeroBeast** 2021-01-22 09:02 UTC
Labels: enhancement
